### PR TITLE
WIP: Implement POM design in `cardano-explorer-node`

### PR DESCRIPTION
**Pull request by Jimbo4350**
This [PR](https://github.com/input-output-hk/cardano-node/pull/271) needs to be merged first and then the `stack.yaml` & `cabal.project` files need to be updated here again. This should fix the log config file issue below.
Before:
```
PGPASSFILE=config/pgpass mainnet-node-local/bin/cardano-explorer-node \
    --log-config ../cardano-node/configuration/log-configuration.yaml \
    --genesis-file ../cardano-node/mainnet-genesis.json \
    --genesis-hash 5f20df933584822601f9e3f8c024eb5eb252fe8cefb24d1317dc3d432e940ebb \
    --socket-path ../cardano-node/state-node-mainnet/socket/node-core-0.socket \
    --schema-dir schema/
Cannot find the logging configuration file at location.
cardano-explorer-node: File not found on path './configuration/log-configuration.yaml'.
```
After:
```
 PGPASSFILE=config/pgpass mainnet-node-local/bin/cardano-explorer-node \                                                                                       
    --log-config ../cardano-node/configuration/log-configuration.yaml \
    --genesis-file ../cardano-node/mainnet-genesis.json \
    --genesis-hash 5f20df933584822601f9e3f8c024eb5eb252fe8cefb24d1317dc3d432e940ebb \
    --socket-dir ../cardano-node/state-node-mainnet/socket/node-core-0.socket \
    --schema-dir schema/
[iohk.cardano.#messagecounters.aggregation:Debug:10] [2019-10-30 17:18:25.68 UTC] time_interval_(s) = 0
[iohk.cardano.#messagecounters.monitoring:Debug:13] [2019-10-30 17:18:25.68 UTC] time_interval_(s) = 0
[iohk.cardano.explorer-db-node:Info:1] [2019-10-30 17:18:25.68 UTC] Initial genesis distribution present and correct
[iohk.cardano.explorer-db-node:Info:1] [2019-10-30 17:18:25.68 UTC] Total genesis supply of Ada: 31112484745.000000
[iohk.cardano.explorer-db-node:Info:1] [2019-10-30 17:18:25.68 UTC] Starting node client
...
```
NB: `--socket-path` is now `--socket-dir`

### CODE REVIEW

**Review by erikd — COMMENTED** [review]
This still seems much more complex than it should be.

The explorer only needs:

* log configuration
* genesis file
* genesis hash
* node socket dir
* schema dir

Anything beyond that should be hidden.

**Comment by erikd** [comment]
How much of the node configuration does the explorer need to provide? Maybe the explorer needs a `--node-config` command line parameter which would then *vastly* simplify everything.

**Comment by Jimbo4350** [comment]
> How much of the node configuration does the explorer need to provide? Maybe the explorer needs a `--node-config` command line parameter which would then _vastly_ simplify everything.

@erikd  So currently I'm working on this. I spoke with @dcoutts yesterday about having the node take a single parameter i.e `--node-config` which you would then provide a `.yaml` file. Then we can ~write `yaml` parsers~ decode the `.yaml` file for that component's configuration needs.

**Comment by cleverca22** [comment]
i would prefer to keep `--socket-path` because `--socket-dir` assumes the filename within the dir is generated based on the node type and index
but explorer doesn't care what type or index the local node is

**Comment by Jimbo4350** [comment]
After speaking with @erikd  we realized that the explorer does not need  `cardano-node` as a dependency.

**Pull request closed without merging**
