### PR TITLE
update ouroboros network depenency

### PR DESCRIPTION
**Pull request by coot**
It seem me and @dcoutts worked on the same thing yesterday.  This updates one step commit further (snockets); but let's first merge #272, I'll then resolve conflicts.

### CODE REVIEW

**Comment by erikd** [comment]
> This updates one step commit further (snockets); but let's first merge #272, I'll then resolve conflicts.

I am not exactly sure what this means, but code that does not build should never be merged to master. In fact code that does not pass "Required" CI should never be merged to master.

**Review by erikd — CHANGES_REQUESTED** [review]
It should compile and pass Required CI before being merged to master.

**Comment by coot** [comment]
> I am not exactly sure what this means, but code that does not build should never be merged to master. 

This PR updates ouroboros-dependency up to one commit more than #272 (which includes snockets - an abstraction over sockets which allows to use clients over NamedPipes on Windows).

> In fact code that does not pass "Required" CI should never be merged to master.

That's crystal clear, and that's never been my intention.

**Comment by erikd** [comment]
Closing this as it was sorted in another PR.

**Pull request closed without merging**
