### PR TITLE
Bump to 1.2.0 and update changelog

### PR DESCRIPTION
**Pull request by mrBliss**
First sync the dependencies with cardano-node-1.2.0

### CODE REVIEW

**Review by coot — APPROVED** [review]
LGTM, though the `cardano-explorer-db` and `cardano-explorer-webapi` do not depend on `ouroboros-network` or `ouroboros-consensus` (as suggested by the change log entery).

**Comment by mrBliss** [comment]
> LGTM, though the `cardano-explorer-db` and `cardano-explorer-webapi` do not depend on `ouroboros-network` or `ouroboros-consensus` (as suggested by the change log entery).

Ah, thanks for catching this! Nothing really changed for these packages, only (indirect) dependency bumps. It feels a bit silly to update their changelog (and even to bump their version number).

**Comment by mrBliss** [comment]
@coot What do you think of my last changes (check the Changelogs)?

**Comment by coot** [comment]
It looks ok for me.

**Pull request merged**
