### PR TITLE
cardano-node: bump to 1.1.0

### PR DESCRIPTION
**Pull request by disassembler**
Uses latest node in docker image.

### CODE REVIEW

**Review by erikd — DISMISSED** [review]
The `explorer` no longer depends on `node` so these sections `node` sections should just be dropped. 

This is another instance of the truth according to Nix being different from the truth according to `cabal`

**Comment by erikd** [comment]
@dcoutts suggested that the `node` dependency is need for the docker container than needs both the `node` and the `explorer`. If that's the case let me know and I will withdraw this PR.

**Comment by tatyanavych** [comment]
We did not release 1.0.0. The code changes should be part of 1.0.0. No version bump is needed - just re-tagging. This PR should be closed @disassembler .

**Comment by disassembler** [comment]
yes, this is for docker image.

**Review by dcoutts — APPROVED** [review]
LGTM.

**Pull request merged**
