### PR TITLE
Nixos tests for exporter

### PR DESCRIPTION
**Pull request by manveru**
Should be merged after #136

### CODE REVIEW

**Review by cleverca22 — APPROVED** [review]

**Review by erikd — COMMENTED** [review]
Before this is merged, can we please clean up the commit history?

**Comment by manveru** [comment]
@erikd this is ready for review.

**Comment by erikd** [comment]
If this does not touch Haskell code I am unqualified to review it. 

However there are a number of what I consider "work in progress" commits in this history that should be squashed down into previous commits.

I consider the Haskell code in this repo to be the primary thing of importance. I also at times use git history to figure out what decisions were made and why, which means I care greatly for a clean, concise and accurate git commit history. That means that afaiac the presence of the Nix updates in the history should be kept to a minimum. My preference would be fore all this PR to be squashed down to a single commit with the main features of this PR listed in point form in the commit message body.

Also, please manuallty squash this down to one commit locally and force push instead of use the GH squash functionality.

**Comment by erikd** [comment]
The two commits from #136 should be rolled into this PR.

**Comment by manveru** [comment]
@erikd I just squashed the commits and rebased on master, but there's a failing build on Hydra now.

https://hydra.iohk.io/build/1329627/nixlog/1

I'm not sure what's going on there, but seems like Haskell stuff :)

**Comment by erikd** [comment]
Currently working on fixing that.

**Comment by cleverca22** [comment]
`git rebase origin/master` shows that all changes are in `master`

**Pull request closed without merging**
